# The current version of Minecraft the project will use
mc_ver=26.2
# Mod Info
mod_name=OneKeyMiner
mod_authors=["Mai_xiyu"]
mod_authors_display=Mai_xiyu
mod_id=onekeyminer
mod_version=1.6.9
group=org.xiyu.onekeyminer
license=LicenseRef-Code-Repository-General-License-v1.2
credits=
description=Server-authoritative chain mining, interaction, planting, and harvesting.

# Gradle
org.gradle.jvmargs=-Xmx6G -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
#org.gradle.configuration-cache=true
org.gradle.java.installations.auto-download=false
