# The current version of Minecraft the project will use
mc_ver=26.2
# Mod Info
mod_name=OneKeyMiner
mod_authors=["Mai_xiyu"]
mod_id=onekeyminer
mod_version=1.6.6
group=org.xiyu.onekeyminer
license=ARR
credits=
mod_description=One-key chained mining with tool interactions, planting, and mature-crop harvesting.

# Manifold
manifold_version=2026.1.6

# Gradle
org.gradle.jvmargs=-Xmx6G -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
#org.gradle.configuration-cache=true
org.gradle.java.installations.auto-download=false
